### ISSUE TITLE
feature request: allow for sources to have different name/identifier

### ISSUE THREAD

**Issue by MarthaScheffler** [arnoN7/dbt-incremental-stream#10]
At the moment, the stream package only supports incremental sources when the identifier of the source is not different from its name.

```
version: 2

sources:
  - name: my_source_name
    database: my_database  
    schema: my_database
    tables:
      - name: my_table
         identifier: identifier_for_my_table
```

The issue arises otherwise during replacement of the `input_model`, when the table_name points towards an identifier and not the actual table.

I tried playing a bit around with the graph variable in macro stream_source:
````
{%- macro stream_source(source_name, table_name) -%}
    {% if execute %}
    {% set source_identifier = graph.sources['source.'~project_name~'.'~source_name~'.'~table_name]['identifier'] %}
    {{incr_stream.stream_input(table_name, 'source', source_name=source_name, source_identifier=source_identifier)}}
    {% endif %}
{%- endmacro -%}
````
but had no luck when replacing some of the table_names in the `stream_input` macro with the source_identifier.

(PS: similar might be interesting for aliasing tables, but in my case I don't use table aliases, while I use source names a lot)
